# Generated by Django 2.2.14 on 2020-11-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201112_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], default='Personal', max_length=1),
            preserve_default=False,
        ),
    ]
