# Generated by Django 2.2.14 on 2020-11-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201112_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='username_field',
        ),
    ]
