# Generated by Django 2.2.14 on 2020-11-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201112_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
