# Generated by Django 2.2.14 on 2020-11-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
