# Generated by Django 2.2.14 on 2020-11-13 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Business', 'Business')], max_length=10),
        ),
    ]
