# Generated by Django 2.2.14 on 2020-11-14 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
